# Generated by Django 4.2.1 on 2023-06-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=1000)),
            ],
        ),
    ]
