# Generated by Django 4.2.1 on 2023-06-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'permissions': [('puede_leer_formulario', 'Permiso para lectura de formularios')]},
        ),
    ]
